#ifndef _HTMLELEM_H_
#define _HTMLELEM_H_

//
// List of all available HTML 4.01 elements
// https://www.w3.org/TR/html4/index/elements.html
//
#define     HTML_ELEM_A             0
#define     HTML_ELEM_ABBR          1
#define     HTML_ELEM_ACRONYM       2
#define     HTML_ELEM_ADDRESS       3
#define     HTML_ELEM_APPLET        4
#define     HTML_ELEM_AREA          5
#define     HTML_ELEM_B             6
#define     HTML_ELEM_BASE          7
#define     HTML_ELEM_BASEFONT      8
#define     HTML_ELEM_BDO           9
#define     HTML_ELEM_BIG           10
#define     HTML_ELEM_BLOCKQUOTE    11
#define     HTML_ELEM_BODY          12
#define     HTML_ELEM_BR            13
#define     HTML_ELEM_BUTTON        14
#define     HTML_ELEM_CAPTION       15
#define     HTML_ELEM_CENTER        16
#define     HTML_ELEM_CITE          17
#define     HTML_ELEM_CODE          18
#define     HTML_ELEM_COL           19
#define     HTML_ELEM_COLGROUP      20
#define     HTML_ELEM_DD            21
#define     HTML_ELEM_DEL           22
#define     HTML_ELEM_DFN           23
#define     HTML_ELEM_DIR           24
#define     HTML_ELEM_DIV           25
#define     HTML_ELEM_DL            26
#define     HTML_ELEM_DT            27
#define     HTML_ELEM_EM            28
#define     HTML_ELEM_FIELDSET      29
#define     HTML_ELEM_FONT          30
#define     HTML_ELEM_FORM          31
#define     HTML_ELEM_FRAME         32
#define     HTML_ELEM_FRAMESET      33
#define     HTML_ELEM_H1            34
#define     HTML_ELEM_H2            35
#define     HTML_ELEM_H3            36
#define     HTML_ELEM_H4            37
#define     HTML_ELEM_H5            38
#define     HTML_ELEM_H6            39
#define     HTML_ELEM_HEAD          40
#define     HTML_ELEM_HR            41
#define     HTML_ELEM_HTML          42
#define     HTML_ELEM_I             43
#define     HTML_ELEM_IFRAME        44
#define     HTML_ELEM_IMG           45
#define     HTML_ELEM_INPUT         46
#define     HTML_ELEM_INS           47
#define     HTML_ELEM_ISINDEX       48
#define     HTML_ELEM_KBD           49
#define     HTML_ELEM_LABEL         50
#define     HTML_ELEM_LEGEND        51
#define     HTML_ELEM_LI            52
#define     HTML_ELEM_LINK          53
#define     HTML_ELEM_MAP           54
#define     HTML_ELEM_MENU          55
#define     HTML_ELEM_META          56
#define     HTML_ELEM_NOFRAMES      57
#define     HTML_ELEM_NOSCRIPT      58
#define     HTML_ELEM_OBJECT        59
#define     HTML_ELEM_OL            60
#define     HTML_ELEM_OPTGROUP      61
#define     HTML_ELEM_OPTION        62
#define     HTML_ELEM_P             63
#define     HTML_ELEM_PARAM         64
#define     HTML_ELEM_PRE           65
#define     HTML_ELEM_Q             66
#define     HTML_ELEM_S             67
#define     HTML_ELEM_SAMP          68
#define     HTML_ELEM_SCRIPT        69
#define     HTML_ELEM_SELECT        70
#define     HTML_ELEM_SMALL         71
#define     HTML_ELEM_SPAN          72
#define     HTML_ELEM_STRIKE        73
#define     HTML_ELEM_STRONG        74
#define     HTML_ELEM_STYLE         75
#define     HTML_ELEM_SUB           76
#define     HTML_ELEM_SUP           77
#define     HTML_ELEM_TABLE         78
#define     HTML_ELEM_TD            79
#define     HTML_ELEM_TEXTAREA      80
#define     HTML_ELEM_TFOOT         81
#define     HTML_ELEM_TH            82
#define     HTML_ELEM_THEAD         83
#define     HTML_ELEM_TITLE         84
#define     HTML_ELEM_TR            85
#define     HTML_ELEM_TT            86
#define     HTML_ELEM_U             87
#define     HTML_ELEM_UL            88
#define     HTML_ELEM_VAR           89
#define     HTML_ELEM_ERROR         255

#endif // _HTMLELEM_H_
